### PR TITLE
Add the configuration files for Docker Compose and CircleCI

### PR DESCRIPTION
**Pull request by dedan**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bob-emploi/3)

### CODE REVIEW

**Comment by dedan** [comment]
+@pcorpet 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-:-KaMRyObn6iMYAbZFtD5:bv2wshd)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 38 at r1](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-KaMU0GDjAFElXAAe_Vk:-KaMU0GDjAFElXAAe_Vl:b-9tzfsw) ([raw file](https://github.com/bayesimpact/bob-emploi/blob/bb23e4656fcb01887aa4b7e9cd848565ef01e6cc/circle.yml#L38)):*
> ```YAML
>     owner: bayesimpact
>     commands:
>       - frontend/release/publish.sh "tag-$CIRCLE_TAG"
> ```

As discussed this is a free ticket for anyone that wants to run some code on our server. Let's postpone it for now.

---

*[docker-compose.yml, line 68 at r1](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-KaMRp4lPRwM7kXoPTEa:-KaMRp4mRsbrwM4JQItH:b6glg4y) ([raw file](https://github.com/bayesimpact/bob-emploi/blob/bb23e4656fcb01887aa4b7e9cd848565ef01e6cc/docker-compose.yml#L68)):*
> ```YAML
>       DEBUG: '1'
>       SERVER_VERSION: local-test
>       FACEBOOK_APP_SECRET: 'aA12bB34cC56dD78eE90fF12aA34bB56'
> ```

Hmm do we really want to share that one? You might need to find a way to clean the history somehow as well…

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-:-KaMU99r6jiY8CWaSmII:bnfp4nl)*

**Comment by dedan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 38 at r1](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-KaMU0GDjAFElXAAe_Vk:-KaMVZcUUXWcl3n-PY9q:b-896fix) ([raw file](https://github.com/bayesimpact/bob-emploi/blob/bb23e4656fcb01887aa4b7e9cd848565ef01e6cc/circle.yml#L38)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

As discussed this is a free ticket for anyone that wants to run some code on our server. Let's postpone it for now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3)*

**Comment by dedan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker-compose.yml, line 68 at r1](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3#-KaMRp4lPRwM7kXoPTEa:-KaMY77R4SzarIZSIiLy:b-896fix) ([raw file](https://github.com/bayesimpact/bob-emploi/blob/bb23e4656fcb01887aa4b7e9cd848565ef01e6cc/docker-compose.yml#L68)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Hmm do we really want to share that one? You might need to find a way to clean the history somehow as well…
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/3)*

**Pull request merged**
