### PR TITLE
Add CircleCI and Docker configuration for the data_analysis module

### PR DESCRIPTION
**Pull request by dedan**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bob-emploi/10)

### CODE REVIEW

**Comment by pcorpet** [comment]
:lgtm: +@pcorpet 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/10#-:-KarkB7FaWsoZj1-MMHY:btvvriz)*

**Comment by dedan** [comment]
You are too fast today ;-) I created this PR only to see if the tests run through. Pushing to a branch would have been enough I realize

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/10#-:-Karn7Q4574xrG__70g2:b-ybq2og)*

**Comment by pcorpet** [comment]
OK, sorry about that -@pcorpet 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/10#-:-KavGI_0XjfpEYQi45NX:b-csyo20)*

**Comment by dedan** [comment]
+@pcorpet And here we go. Ready for you Monsieur 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/10#-:-KawHF816IWBSy9I5YxI:b-abayyz)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bob-emploi/10#-:-KaxrTDRs8y7vOT0RpGd:bnfp4nl)*

**Pull request merged**
